dbt_project:
  target: snowflake  
  outputs:
    snowflake:
      type: snowflake
      account: 
      user: 
      password: 
      role: 
      database: 
      warehouse: 
      schema: 
      threads: 1
