# for getting data from Snowflake
SNOWFLAKE_USER: 
SNOWFLAKE_PASSWORD: 
SNOWFLAKE_ACCOUNT: 
SNOWFLAKE_WAREHOUSE: 
SNOWFLAKE_DATABASE: 
SNOWFLAKE_SCHEMA: 

AWS_ROLE_ARN: 
AWS_ALLOWED_LOCATIONS: ('s3://bucket_name/')
AWS_EXTERNAL_ID : 
  
  # AWS
AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
AWS_REGION:
AWS_BUCKET_NAME:
